branch-defaults:
  master:
    environment: ShareAMeal-env
environment-defaults:
  ShareAMeal-env:
    branch: master
    repository: shared-meal-api
global:
  application_name: share-a-meal
  default_ec2_keyname: aws-eb
  default_platform: Docker 17.03.2-ce
  default_region: ap-south-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  sc: git
  workspace_type: Application
