application: share-a-meal-api
version: 2
some_time: $CIRCLE_BUILD_NUM
jobs:
  build:
    working_directory: ~/share-a-meal-api
    docker:
      - image: docker:17.05.0-ce-git
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Docker Login
          command: docker login -u "tanmayawasekar" -p "7825bheja"
      - run:
          name: Docker Build
          command: docker build -t "tanmayawasekar/share-a-meal-api:$some_time" .
      - run:
          name: Docker Push
          command: docker push "tanmayawasekar/share-a-meal-api:$some_time" 
  test:
    working_directory: ~/share-a-meal-api
    docker:
      - image: tanmayawasekar/share-a-meal-api:$some_time
    steps:
      - checkout
      - run:
          name: Install npm process
          command: npm i process-nextick-args util-deprecate
      - run: 
          name: Npm Install
          command: npm install
      - run:
          name: Test
          command: npm test
workflows:
  version: 2
  build_and_test_and_deploy:
    jobs:
      - build
      - test:
          requires:
            - build
          filters:
            branches:
              only: master