version: 2
jobs:
   build:
     docker:
       - image: circleci/node:6
     steps:
       - checkout
       - run: echo "hello world"

#        machine:
#   services:
#     - docker
#   python:
#     version: 2.7
# dependencies:
#   pre:
#     - sudo apt-get install python-dev
#     - pip install awsebcli
# deployment:
#   production:
#     branch: master
#     commands:
#       - docker login -e "tanmayawasekar@gmail.com" -u "tanmayawasekar" -p "7825bheja"
#       - docker build -t "tanmayawasekar/share-a-meal-api:$CIRCLE_BUILD_NUM" .
#       # - docker push "tanmayawasekar/share-a-meal-api:$CIRCLE_BUILD_NUM"
#       - sed -i'' -e "s;%BUILD_NUM%;$CIRCLE_BUILD_NUM;g" ./.deploy/Dockerrun.aws.json
#       - bash ./setup-eb.sh
#       -  eb init
#       -  eb deploy -l $CIRCLE_BUILD_NUM
