application: share-a-meal-api
version: 2
jobs:
  build:
    working_directory: ~/share-a-meal-api
    docker:
      - image: docker:17.05.0-ce-git
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build 1
          command: docker login -u "tanmayawasekar" -p "7825bheja"
      - run:
          name: Build 2
          command: docker build -t "tanmayawasekar/share-a-meal-api:$CIRCLE_BUILD_NUM" .
      - run:
          name: Build 3
          command: docker push "tanmayawasekar/share-a-meal-api:$CIRCLE_BUILD_NUM" 
  test:
    working_directory: ~/share-a-meal-api
    docker:
      - image: tanmayawasekar/share-a-meal-api:$CIRCLE_BUILD_NUM
    steps:
      - checkout
      - run:
          name: Install npm process
          command: npm i process-nextick-args util-deprecate
      - run: 
          name: Npm Install
          command: npm install
workflows:
  version: 2
  build_and_test_and_deploy:
    jobs:
      - test
      - build:
          requires:
            - test
