version: 2
jobs:
  build:
    working_directory: ~/share-a-meal-api
    # The primary container is an instance of the first list image listed. Your build commands run in this container.
    docker:
      - image: circleci/node:6
    # The secondary container is an instance of the second listed image which is run in a common network where ports exposed on the primary container are available on localhost.   
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Install npm process
          command: npm i process-nextick-args util-deprecate
      - run: 
          name: Npm Install
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - node_modules
      - run:
          name: Test
          command: npm test
      - store_artifacts:
          path: test-results.xml
          prefix: tests
      - store_artifacts:
          path: coverage
          prefix: coverage
      - run:
          name: wow
          command: |
            # sudo add-apt-repository ppa:jonathonf/python-3.6
            sudo apt-get update
            sudo apt-get install python3.6
            sudo apt-get install python-dev
            pip install awsebcli
            docker login -e "tanmayawasekar@gmail.com" -u "tanmayawasekar" -p "7825bheja"
            docker build -t "tanmayawasekar/share-a-meal-api:$CIRCLE_BUILD_NUM" .
            sed -i'' -e "s;%BUILD_NUM%;$CIRCLE_BUILD_NUM;g" ./.deploy/Dockerrun.aws.json
            eb deploy -l $CIRCLE_BUILD_NUM
      
workflows:
  version: 2
  build:
    jobs:
      - build
